import type { ComponentDefinition } from "@ui-builder/builder-core";
import { NavigationMenuRuntime } from "./navigation-menu/NavigationMenuRuntime";
import { DEFAULT_ITEMS, ITEM_STYLE_OPTIONS } from "./navigation-menu/types";

export const NavigationMenuComponent: ComponentDefinition = {
  type: "NavigationMenu",
  name: "Navigation Menu",
  category: "navigation",
  group: "menu",
  subGroup: "menu-horizontal",
  description: "Responsive navigation with anchors, page links, submenu items, overflow handling, and hamburger menus.",
  version: "2.0.0",
  tags: ["menu", "navigation", "nav", "header", "hamburger", "responsive", "submenu", "anchor"],
  capabilities: {
    canContainChildren: false,
    canResize: true,
    canTriggerEvents: true,
    canBindData: true,
    canBeHidden: true,
    canBeLocked: true,
  },
  aiHints: {
    purpose: "Responsive navigation menu with anchor/page/url targets, nested submenu items, overflow handling, and hamburger overlay.",
    bestFor: ["header navigation", "footer links", "anchor navigation", "multi-page navigation", "mobile hamburger menus"],
    sectionAffinity: ["header", "footer"],
    contentSlots: { items: { prop: "items", shape: "array-of-objects", itemKeys: { title: "label", href: "target" }, maxItems: 6 } },
    fallbackTo: ["Row", "Text", "Button"],
    examples: ["Header nav linking to section anchors (Services, Pricing, FAQ)"],
  },
  propSchema: [
    { key: "items", label: "Menu Items (tree JSON)", type: "json", required: true },
    {
      key: "orientation",
      label: "Orientation",
      type: "select",
      options: [
        { value: "horizontal", label: "Horizontal" },
        { value: "vertical", label: "Vertical" },
      ],
      default: "horizontal",
    },
    {
      key: "mobileBehavior",
      label: "Mobile Behavior",
      type: "select",
      options: [
        { value: "hamburger", label: "Hamburger" },
        { value: "keep", label: "Keep menu" },
      ],
      default: "hamburger",
    },
    {
      key: "hamburgerMode",
      label: "Hamburger Mode",
      type: "select",
      options: [
        { value: "fullscreen", label: "Full screen" },
        { value: "drawer", label: "Side drawer" },
        { value: "dropdown", label: "Dropdown" },
      ],
      default: "fullscreen",
    },
    {
      key: "itemStyle",
      label: "Item Style",
      type: "select",
      options: ITEM_STYLE_OPTIONS.map((value) => ({ value, label: value.split("-").map((part) => part[0]!.toUpperCase() + part.slice(1)).join(" ") })),
      default: "plain",
    },
    { key: "textColor", label: "Text Color", type: "color", default: "#111827" },
    { key: "activeColor", label: "Active Color", type: "color", default: "#2563eb" },
    { key: "activeBg", label: "Active Item Background", type: "color", default: "" },
    { key: "itemBg", label: "Item Background", type: "color", default: "" },
    { key: "navBg", label: "Nav Background", type: "color", default: "" },
    { key: "navBorder", label: "Nav Border (CSS)", type: "string", default: "" },
    { key: "navBorderRadius", label: "Nav Border Radius", type: "string", default: "" },
    { key: "navPadding", label: "Nav Padding", type: "string", default: "" },
    { key: "fontSize", label: "Font Size", type: "string", default: "14px" },
    { key: "letterSpacing", label: "Letter Spacing", type: "string", default: "" },
    { key: "itemGap", label: "Horizontal Spacing", type: "number", default: 24, min: 0, max: 96, step: 2, unit: "px" },
    { key: "rowGap", label: "Vertical Spacing", type: "number", default: 8, min: 0, max: 80, step: 2, unit: "px" },
    { key: "dropdownPadding", label: "Dropdown Padding", type: "number", default: 12, min: 0, max: 40, step: 1, unit: "px" },
    { key: "dropdownRadius", label: "Dropdown Radius", type: "number", default: 12, min: 0, max: 32, step: 1, unit: "px" },
    { key: "dropdownMinWidth", label: "Dropdown Min Width", type: "number", default: 210, min: 120, max: 420, step: 10, unit: "px" },
    { key: "dropdownBg", label: "Dropdown Background", type: "color", default: "" },
    { key: "dropdownBorderColor", label: "Dropdown Border", type: "color", default: "" },
    { key: "dropdownItemHoverBg", label: "Dropdown Hover", type: "color", default: "" },
    {
      key: "dropdownShadow",
      label: "Dropdown Shadow",
      type: "select",
      options: [
        { value: "none", label: "None" },
        { value: "soft", label: "Soft" },
        { value: "deep", label: "Deep" },
      ],
      default: "soft",
    },
    { key: "dropdownOffsetX", label: "Dropdown Offset X", type: "number", default: 0, min: -80, max: 80, step: 1, unit: "px" },
    { key: "dropdownOffsetY", label: "Dropdown Offset Y", type: "number", default: 0, min: -40, max: 80, step: 1, unit: "px" },
    { key: "fillItems", label: "Fill Whole Menu", type: "boolean", default: false },
    {
      key: "overflowMode",
      label: "Overflow Mode",
      type: "select",
      options: [
        { value: "wrap", label: "Wrap" },
        { value: "scroll", label: "Scroll" },
        { value: "collapse", label: "More menu" },
      ],
      default: "wrap",
    },
    {
      key: "widthMode",
      label: "Width Mode",
      type: "select",
      options: [
        { value: "wrap", label: "Wrap" },
        { value: "fullWidth", label: "Full width" },
      ],
      default: "wrap",
    },
    {
      key: "alignment",
      label: "Alignment",
      type: "select",
      options: [
        { value: "left", label: "Left" },
        { value: "center", label: "Center" },
        { value: "right", label: "Right" },
        { value: "justify", label: "Justify" },
      ],
      default: "left",
    },
  ],
  defaultProps: {
    items: DEFAULT_ITEMS,
    orientation: "horizontal",
    layout: "horizontal",
    mobileBehavior: "hamburger",
    mobileHamburger: true,
    hamburgerMode: "fullscreen",
    dropdownMode: "flyout",
    dropdownWidthMode: "fitToMenu",
    dropdownColumns: 3,
    dropdownAlignment: "left",
    widthMode: "wrap",
    overflowMode: "wrap",
    fillItems: false,
    alignment: "left",
    textColor: "#111827",
    activeColor: "#2563eb",
    activeBg: "",
    itemBg: "",
    navBg: "",
    navBorder: "",
    navBorderRadius: "",
    navPadding: "",
    fontSize: "14px",
    letterSpacing: "",
    itemGap: 24,
    rowGap: 8,
    dropdownGap: 8,
    columnGap: 30,
    dropdownMargin: 10,
    dropdownPadding: 12,
    dropdownRadius: 12,
    dropdownMinWidth: 210,
    dropdownShadow: "soft",
    dropdownBg: "",
    dropdownBorderColor: "",
    dropdownItemHoverBg: "",
    dropdownOffsetX: 0,
    dropdownOffsetY: 0,
    activeMode: "auto",
    activeItemId: "",
    activeIndex: 0,
    itemStyle: "plain",
    floatingMode: "static",
  },
  defaultStyle: { width: "100%", padding: "0 16px", display: "flex", alignItems: "center" },
  a11y: {
    role: "navigation",
    ariaLabel: "Site navigation",
    focusable: false,
  },
  editorRenderer: ({ node, style, breakpoint }) => <NavigationMenuRuntime node={node} style={style} mode="editor" breakpoint={breakpoint} />,
  runtimeRenderer: ({ node, style, breakpoint }) => <NavigationMenuRuntime node={node} style={style} mode="runtime" breakpoint={breakpoint} />,
};
