import type { PopupTemplate } from "@ui-builder/builder-core";

export const DEFAULT_POPUP_TEMPLATES: PopupTemplate[] = [
  {
    id: "newsletter-modal",
    name: "Newsletter Modal",
    description: "Centered signup modal with headline, copy, and CTA.",
    category: "Lead capture",
    tags: ["newsletter", "modal", "lead"],
    popup: {
      name: "Newsletter Modal",
      enabled: true,
      kind: "modal",
      placement: "center",
      kindConfig: { kind: "modal", size: "md", maxWidth: "560px", maxHeight: "90vh" },
      autoTrigger: { type: "manual" },
      behavior: {
        backdrop: { enabled: true, color: "#020617", opacity: 0.5, blur: "3px" },
        closeOnEscape: true,
        closeOnBackdropClick: true,
        showCloseButton: true,
        lockBodyScroll: true,
        trapFocus: true,
        restoreFocus: true,
      },
      animation: { enter: "scale", exit: "scale", durationMs: 200, easing: "ease" },
      rules: {},
    },
    root: {
      componentType: "PopupContent",
      style: { borderRadius: "18px", padding: "36px", gap: "18px", alignItems: "center", textAlign: "center" },
      children: [
        {
          componentType: "Text",
          props: { tag: "h2", text: "<h2>Join the list</h2>" },
          style: { fontSize: "32px", fontWeight: 700, lineHeight: "1.1", width: "100%", color: "#0f172a" },
        },
        {
          componentType: "Text",
          props: { tag: "p", text: "<p>Get launch notes, design ideas, and useful updates in your inbox.</p>" },
          style: { fontSize: "15px", color: "#475569", width: "100%", maxWidth: "420px" },
        },
        {
          componentType: "Button",
          props: { label: "<span>Subscribe</span>", variant: "primary" },
          style: { width: "180px" },
        },
      ],
    },
  },
  {
    id: "promo-drawer",
    name: "Promo Drawer",
    description: "Right-side offer drawer.",
    category: "Promotion",
    tags: ["promo", "drawer", "offer"],
    popup: {
      name: "Promo Drawer",
      enabled: true,
      kind: "drawer",
      placement: "right",
      kindConfig: { kind: "drawer", width: "420px", minWidth: "320px", maxWidth: "86vw", resizable: false },
      autoTrigger: { type: "manual" },
      behavior: {
        backdrop: { enabled: true, color: "#020617", opacity: 0.42, blur: "2px" },
        closeOnEscape: true,
        closeOnBackdropClick: true,
        showCloseButton: true,
        lockBodyScroll: true,
        trapFocus: true,
        restoreFocus: true,
      },
      animation: { enter: "slide-left", exit: "slide-right", durationMs: 220, easing: "ease" },
      rules: {},
    },
    root: {
      componentType: "PopupContent",
      style: { minHeight: "100vh", padding: "40px 28px", gap: "20px" },
      children: [
        { componentType: "Text", props: { tag: "h2", text: "<h2>Special offer</h2>" }, style: { fontSize: "30px", fontWeight: 700, width: "100%" } },
        { componentType: "Text", props: { tag: "p", text: "<p>Use this space for a time-sensitive campaign or product announcement.</p>" }, style: { color: "#475569", width: "100%" } },
        { componentType: "Button", props: { label: "<span>Claim offer</span>", variant: "primary" }, style: { width: "100%" } },
      ],
    },
  },
  {
    id: "mobile-bottom-sheet",
    name: "Mobile Bottom Sheet",
    description: "Compact bottom sheet for mobile CTAs.",
    category: "Mobile",
    tags: ["bottom sheet", "mobile", "cta"],
    popup: {
      name: "Mobile Bottom Sheet",
      enabled: true,
      kind: "bottomSheet",
      placement: "bottom",
      kindConfig: { kind: "bottomSheet", initialHeight: "42vh", minHeight: "180px", maxHeight: "92vh", snapPoints: ["25vh", "42vh", "86vh"], draggable: true, dragToClose: true },
      autoTrigger: { type: "manual" },
      behavior: {
        backdrop: { enabled: true, color: "#020617", opacity: 0.38, blur: "2px" },
        closeOnEscape: true,
        closeOnBackdropClick: true,
        showCloseButton: true,
        lockBodyScroll: true,
        trapFocus: true,
        restoreFocus: true,
      },
      animation: { enter: "slide-up", exit: "slide-down", durationMs: 240, easing: "ease" },
      rules: { devices: ["mobile"] },
    },
    root: {
      componentType: "PopupContent",
      style: { borderRadius: "18px 18px 0 0", padding: "30px 22px", gap: "14px" },
      children: [
        { componentType: "Text", props: { tag: "h3", text: "<h3>Ready when you are</h3>" }, style: { fontSize: "24px", fontWeight: 700, width: "100%" } },
        { componentType: "Button", props: { label: "<span>Continue</span>", variant: "primary" }, style: { width: "100%" } },
      ],
    },
  },
  {
    id: "announcement-bar",
    name: "Announcement Bar",
    description: "Top or bottom site announcement.",
    category: "Announcement",
    tags: ["bar", "announcement"],
    popup: {
      name: "Announcement Bar",
      enabled: true,
      kind: "bar",
      placement: "top",
      kindConfig: { kind: "bar", height: "72px", sticky: true, pushPageContent: false },
      autoTrigger: { type: "pageLoad", delayMs: 0 },
      behavior: {
        backdrop: { enabled: false, color: "#000000", opacity: 0 },
        closeOnEscape: true,
        closeOnBackdropClick: false,
        showCloseButton: true,
        lockBodyScroll: false,
        trapFocus: false,
        restoreFocus: true,
      },
      animation: { enter: "slide-down", exit: "slide-up", durationMs: 180, easing: "ease" },
      rules: {},
    },
    root: {
      componentType: "PopupContent",
      style: { minHeight: "72px", padding: "16px 56px 16px 24px", alignItems: "center", justifyContent: "center", backgroundColor: "#0f172a", color: "#ffffff" },
      children: [
        { componentType: "Text", props: { tag: "p", text: "<p>New release is live. Explore the latest updates.</p>" }, style: { color: "#ffffff", width: "100%", textAlign: "center" } },
      ],
    },
  },
  {
    id: "fullscreen-lead",
    name: "Fullscreen Lead",
    description: "Immersive full-screen lead capture.",
    category: "Lead capture",
    tags: ["fullscreen", "lead"],
    popup: {
      name: "Fullscreen Lead",
      enabled: true,
      kind: "fullscreen",
      placement: "center",
      kindConfig: { kind: "fullscreen" },
      autoTrigger: { type: "manual" },
      behavior: {
        backdrop: { enabled: true, color: "#020617", opacity: 0.72, blur: "4px" },
        closeOnEscape: true,
        closeOnBackdropClick: false,
        showCloseButton: true,
        lockBodyScroll: true,
        trapFocus: true,
        restoreFocus: true,
      },
      animation: { enter: "fade", exit: "fade", durationMs: 180, easing: "ease" },
      rules: {},
    },
    root: {
      componentType: "PopupContent",
      style: { minHeight: "100vh", padding: "80px 32px", alignItems: "center", justifyContent: "center", textAlign: "center", backgroundColor: "#f8fafc" },
      children: [
        { componentType: "Text", props: { tag: "h1", text: "<h1>One focused offer</h1>" }, style: { fontSize: "56px", fontWeight: 800, lineHeight: "1", width: "100%", maxWidth: "780px" } },
        { componentType: "Text", props: { tag: "p", text: "<p>Use fullscreen popups sparingly for high-intent moments.</p>" }, style: { fontSize: "18px", color: "#475569", width: "100%", maxWidth: "520px" } },
        { componentType: "Button", props: { label: "<span>Get started</span>", variant: "primary" }, style: { width: "180px" } },
      ],
    },
  },
];
