import { describe, expect, it } from "vitest";
import { ALLOWED_AI_COMMANDS } from "./allowedCommands";

/**
 * Contract test — see docs/roadmap/00-bugfixes/05-command-whitelist-mismatch.md.
 *
 * apps/api (COMMAND_REFERENCE, what the LLM is taught) and this package (what the
 * client will dispatch) live in separate workspaces and cannot import each other's
 * source, so the shared contract is enforced by mirroring the same expected list on
 * both sides: apps/api/src/services/command-reference.test.ts asserts the identical
 * set. If you change one, change both (and command-reference.ts / allowedCommands.ts).
 */
const EXPECTED_COMMAND_TYPES = [
  "ADD_NODE",
  "UPDATE_STYLE",
  "UPDATE_PROPS",
  "RENAME_NODE",
  "UPDATE_RESPONSIVE_STYLE",
  "UPDATE_RESPONSIVE_PROPS",
  "TOGGLE_RESPONSIVE_HIDDEN",
  "RESET_RESPONSIVE_STYLE",
  "DUPLICATE_NODE",
  "UPDATE_CANVAS_CONFIG",
  "UPDATE_INTERACTIONS",
  // Internal-only: generated by the backend for fullPageMode, never suggested by the
  // LLM directly (not part of COMMAND_REFERENCE) — but the client must still allow it
  // through, since it arrives in the same command batch as LLM-authored commands.
  "REMOVE_NODE",
];

describe("ALLOWED_AI_COMMANDS", () => {
  it("matches the command types documented for the LLM in apps/api COMMAND_REFERENCE", () => {
    expect([...ALLOWED_AI_COMMANDS].sort()).toEqual([...EXPECTED_COMMAND_TYPES].sort());
  });

  it("never allows destructive/system commands (deny-by-default)", () => {
    const denied = [
      "MOVE_NODE",
      "REMOVE_NODES",
      "CREATE_POPUP",
      "UPDATE_POPUP",
      "DELETE_POPUP",
      "SET_THEME_COLORS",
      "SET_CANVAS_MODE",
    ];
    for (const type of denied) {
      expect(ALLOWED_AI_COMMANDS.has(type)).toBe(false);
    }
  });
});
